const express = require('express');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const multer = require('multer');
const { pool, hashPassword, validPassword, publicUser, currentUser, createSession, sessionCookie } = require('./auth');
const { ok, fail } = require('./response');

const upload = multer({ dest: path.join(__dirname, '..', 'uploads'), limits: { fileSize: 5 * 1024 * 1024 } });
const root = path.join(__dirname, '..');
const app = express();
app.use(express.json({ limit: '1mb' }));
app.use(express.urlencoded({ extended: true }));
app.use(express.static(root, { index: false }));
const clientDist = path.join(root, 'client-dist');
if (fs.existsSync(clientDist)) app.use('/react', express.static(clientDist));

const input = value => String(value || '').trim();
async function requireUser(request, response, next) {
  try { request.user = await currentUser(request); if (!request.user) return fail(response, 401, 'Authentication required.'); next(); }
  catch (error) { next(error); }
}
function userQueryFields() { return 'id,username,email,display_name,bio,profile_photo_url,is_admin'; }

app.get('/api/health', (_request, response) => ok(response, { status: 'healthy' }));
app.post('/api/auth/signup', async (request, response, next) => {
  try {
    const data = request.body; const username = input(data.username).toLowerCase(); const email = input(data.email || data.identifier).toLowerCase(); const name = input(data.name || data.displayName || username); const password = String(data.password || '');
    if (!/^[a-z0-9_]{3,30}$/.test(username) || !/^\S+@\S+\.\S+$/.test(email) || password.length < 8 || !name) return fail(response, 400, 'Use a valid username, email, name, and password of at least 8 characters.');
    const user = (await pool.query(`INSERT INTO users(username,email,password_hash,display_name) VALUES($1,$2,$3,$4) RETURNING ${userQueryFields()}`, [username, email, await hashPassword(password), name])).rows[0];
    await pool.query('INSERT INTO user_settings(user_id) VALUES($1) ON CONFLICT DO NOTHING', [user.id]);
    response.set('Set-Cookie', sessionCookie(await createSession(user.id))); return ok(response, { user: publicUser(user) }, 201);
  } catch (error) { next(error); }
});
app.post('/api/auth/login', async (request, response, next) => {
  try { const identity = input(request.body.identity || request.body.identifier || request.body.email).toLowerCase(); const user = (await pool.query(`SELECT ${userQueryFields()},password_hash FROM users WHERE LOWER(username)=$1 OR LOWER(email)=$1`, [identity])).rows[0]; if (!user || !(await validPassword(String(request.body.password || ''), user.password_hash))) return fail(response, 401, 'Invalid username/email or password.'); response.set('Set-Cookie', sessionCookie(await createSession(user.id))); return ok(response, { user: publicUser(user) }); } catch (error) { next(error); }
});
app.post('/api/auth/logout', async (request, response, next) => { try { const token = request.headers.cookie?.match(/(?:^|; )sc_session=([^;]*)/)?.[1]; if (token) await pool.query('DELETE FROM sessions WHERE token_hash=$1', [require('./auth').digest(decodeURIComponent(token))]); response.set('Set-Cookie', sessionCookie('', true)); return ok(response); } catch (error) { next(error); } });
app.post('/api/auth/forgot-password', async (request, response, next) => { try { const email = input(request.body.email).toLowerCase(); const user = (await pool.query('SELECT id FROM users WHERE LOWER(email)=$1', [email])).rows[0]; if (!user) return ok(response, { message: 'If that email exists, reset instructions have been created.' }); const token = crypto.randomBytes(32).toString('hex'); await pool.query("INSERT INTO password_reset_tokens(token_hash,user_id,expires_at) VALUES($1,$2,NOW()+INTERVAL '1 hour')", [crypto.createHash('sha256').update(token).digest('hex'), user.id]); return ok(response, { message: 'Reset token created. Connect an email provider before exposing this token to users.', resetToken: token }); } catch (error) { next(error); } });
app.post('/api/auth/reset-password', async (request, response, next) => { try { const token = input(request.body.token); const password = String(request.body.password || ''); if (password.length < 8) return fail(response, 400, 'Password must be at least 8 characters.'); const hash = crypto.createHash('sha256').update(token).digest('hex'); const row = (await pool.query("SELECT user_id FROM password_reset_tokens WHERE token_hash=$1 AND expires_at>NOW() AND used_at IS NULL", [hash])).rows[0]; if (!row) return fail(response, 400, 'Reset token is invalid or expired.'); await pool.query('UPDATE users SET password_hash=$1 WHERE id=$2', [await require('./auth').hashPassword(password), row.user_id]); await pool.query('UPDATE password_reset_tokens SET used_at=NOW() WHERE token_hash=$1', [hash]); return ok(response); } catch (error) { next(error); } });
app.get('/api/auth/me', requireUser, (request, response) => ok(response, { user: publicUser(request.user) }));

app.use('/api', requireUser);
app.get('/api/users/search', async (request, response, next) => { try { const q = `%${input(request.query.q).toLowerCase()}%`; const rows = (await pool.query(`SELECT ${userQueryFields()} FROM users WHERE id<>$1 AND (LOWER(username) LIKE $2 OR LOWER(display_name) LIKE $2) ORDER BY username LIMIT 20`, [request.user.id, q])).rows; return ok(response, { users: rows.map(publicUser) }); } catch (error) { next(error); } });
app.get('/api/profile', (request, response) => ok(response, { user: publicUser(request.user) }));
app.patch('/api/profile', async (request, response, next) => { try { const name = input(request.body.displayName || request.body.name) || request.user.display_name; const bio = input(request.body.bio); const row = (await pool.query('UPDATE users SET display_name=$1,bio=$2 WHERE id=$3 RETURNING ' + userQueryFields(), [name, bio, request.user.id])).rows[0]; return ok(response, { user: publicUser(row) }); } catch (error) { next(error); } });
app.post('/api/profile/photo', upload.single('photo'), async (request, response, next) => { try { if (!request.file) return fail(response, 400, 'Photo is required.'); const url = `/uploads/${request.file.filename}`; const row = (await pool.query('UPDATE users SET profile_photo_url=$1 WHERE id=$2 RETURNING ' + userQueryFields(), [url, request.user.id])).rows[0]; return ok(response, { user: publicUser(row) }); } catch (error) { next(error); } });
app.delete('/api/profile/photo', async (request, response, next) => { try { await pool.query('UPDATE users SET profile_photo_url=NULL WHERE id=$1', [request.user.id]); return ok(response); } catch (error) { next(error); } });

app.get('/api/connections', async (request, response, next) => { try { const connections = (await pool.query(`SELECT u.* FROM connections c JOIN users u ON u.id=c.friend_id WHERE c.user_id=$1 ORDER BY u.username`, [request.user.id])).rows.map(publicUser); return ok(response, { connections, users: connections }); } catch (error) { next(error); } });
app.get('/api/connections/requests', async (request, response, next) => { try { const incoming = (await pool.query(`SELECT cr.id AS request_id,u.* FROM connection_requests cr JOIN users u ON u.id=cr.sender_id WHERE cr.receiver_id=$1 AND cr.status='pending'`, [request.user.id])).rows.map(row => ({ ...publicUser(row), id: row.request_id, requestId: row.request_id, userId: row.id })); const outgoing = (await pool.query(`SELECT cr.id AS request_id,u.* FROM connection_requests cr JOIN users u ON u.id=cr.receiver_id WHERE cr.sender_id=$1 AND cr.status='pending'`, [request.user.id])).rows.map(row => ({ ...publicUser(row), requestId: row.request_id, userId: row.id })); return ok(response, { incoming, outgoing }); } catch (error) { next(error); } });
app.post('/api/connections/request', async (request, response, next) => { try { const target = Number(request.body.userId); if (!target || target === request.user.id) return fail(response, 400, 'Invalid connection target.'); const connectionRequest = (await pool.query('INSERT INTO connection_requests(sender_id,receiver_id) VALUES($1,$2) RETURNING id', [request.user.id, target])).rows[0]; await pool.query("INSERT INTO notifications(user_id,type,title,body,actor_id,request_id) VALUES($1,'connection_request','New connection request',$2,$3,$4)", [target, `${request.user.display_name} wants to connect with you.`, request.user.id, connectionRequest.id]); return ok(response, {}, 201); } catch (error) { next(error); } });
app.post('/api/connections/requests/:id/:action(accept|reject)', async (request, response, next) => { try { const status = request.params.action === 'accept' ? 'accepted' : 'declined'; const row = (await pool.query("UPDATE connection_requests SET status=$1,updated_at=NOW() WHERE id=$2 AND receiver_id=$3 AND status='pending' RETURNING sender_id", [status, request.params.id, request.user.id])).rows[0]; if (!row) return fail(response, 404, 'Request not found.'); await pool.query('UPDATE notifications SET read_at=NOW() WHERE request_id=$1', [request.params.id]); if (status === 'accepted') await pool.query('INSERT INTO connections(user_id,friend_id) VALUES($1,$2),($2,$1) ON CONFLICT DO NOTHING', [request.user.id, row.sender_id]); return ok(response); } catch (error) { next(error); } });
app.delete('/api/connections/requests/:id', async (request, response, next) => { try { await pool.query("DELETE FROM connection_requests WHERE id=$1 AND sender_id=$2 AND status='pending'", [request.params.id, request.user.id]); return ok(response); } catch (error) { next(error); } });

app.get('/api/notifications', async (request, response, next) => { try { const notifications = (await pool.query("SELECT n.*,u.display_name AS actor_name FROM notifications n LEFT JOIN users u ON u.id=n.actor_id WHERE n.user_id=$1 ORDER BY n.created_at DESC LIMIT 50", [request.user.id])).rows; return ok(response, { notifications }); } catch (error) { next(error); } });
app.get('/api/feed', async (request, response, next) => { try { const feed = (await pool.query(`SELECT p.*,u.username,u.display_name FROM posts p JOIN users u ON u.id=p.user_id WHERE p.user_id=$1 OR p.user_id IN (SELECT friend_id FROM connections WHERE user_id=$1) ORDER BY p.created_at DESC LIMIT 50`, [request.user.id])).rows; return ok(response, { feed }); } catch (error) { next(error); } });
app.post('/api/posts', async (request, response, next) => { try { const content = input(request.body.content); if (!content) return fail(response, 400, 'Post content is required.'); const post = (await pool.query('INSERT INTO posts(user_id,content,place_id) VALUES($1,$2,$3) RETURNING *', [request.user.id, content, request.body.placeId || null])).rows[0]; return ok(response, { post }, 201); } catch (error) { next(error); } });
app.post('/api/places/:placeId/rating', async (request, response, next) => { try { const rating = Number(request.body.rating); if (!Number.isInteger(rating) || rating < 1 || rating > 5) return fail(response, 400, 'Rating must be an integer from 1 to 5.'); const row = (await pool.query('INSERT INTO place_ratings(place_id,user_id,rating,review) VALUES($1,$2,$3,$4) ON CONFLICT(place_id,user_id) DO UPDATE SET rating=EXCLUDED.rating,review=EXCLUDED.review,updated_at=NOW() RETURNING *', [request.params.placeId, request.user.id, rating, input(request.body.review)])).rows[0]; return ok(response, { rating: row }); } catch (error) { next(error); } });
app.post('/api/invite', async (request, response, next) => { try { const code = crypto.randomBytes(5).toString('hex'); await pool.query('INSERT INTO invites(code,user_id) VALUES($1,$2)', [code, request.user.id]); return ok(response, { code }, 201); } catch (error) { next(error); } });
app.post('/api/reactions', async (request, response, next) => { try { const itemType = input(request.body.itemType); const itemId = input(request.body.itemId); const reaction = input(request.body.reaction); if (!['place', 'news'].includes(itemType) || !itemId || !['like', 'dislike'].includes(reaction)) return fail(response, 400, 'Invalid reaction.'); await pool.query('INSERT INTO content_reactions(user_id,item_type,item_id,reaction) VALUES($1,$2,$3,$4) ON CONFLICT(user_id,item_type,item_id) DO UPDATE SET reaction=EXCLUDED.reaction', [request.user.id, itemType, itemId, reaction]); return ok(response); } catch (error) { next(error); } });
app.post('/api/circles', async (request, response, next) => { try { const name = input(request.body.name); if (!name) return fail(response, 400, 'Circle name is required.'); const circle = (await pool.query('INSERT INTO circles(owner_id,name) VALUES($1,$2) RETURNING *', [request.user.id, name])).rows[0]; await pool.query("INSERT INTO circle_members(circle_id,user_id,role) VALUES($1,$2,'owner')", [circle.id, request.user.id]); return ok(response, { circle }, 201); } catch (error) { next(error); } });
app.get('/api/circles', async (request, response, next) => { try { const circles = (await pool.query('SELECT c.* FROM circles c JOIN circle_members cm ON cm.circle_id=c.id WHERE cm.user_id=$1 ORDER BY c.created_at DESC', [request.user.id])).rows; return ok(response, { circles }); } catch (error) { next(error); } });
app.post('/api/circles/:circleId/messages', async (request, response, next) => { try { const content = input(request.body.content); const member = await pool.query('SELECT 1 FROM circle_members WHERE circle_id=$1 AND user_id=$2', [request.params.circleId, request.user.id]); if (!member.rowCount) return fail(response, 403, 'You are not a member of this circle.'); if (!content) return fail(response, 400, 'Message is required.'); const message = (await pool.query('INSERT INTO messages(circle_id,sender_id,content) VALUES($1,$2,$3) RETURNING *', [request.params.circleId, request.user.id, content])).rows[0]; return ok(response, { message }, 201); } catch (error) { next(error); } });
app.get('/api/circles/:circleId/messages', async (request, response, next) => { try { const messages = (await pool.query('SELECT m.*,u.display_name FROM messages m JOIN users u ON u.id=m.sender_id JOIN circle_members cm ON cm.circle_id=m.circle_id WHERE m.circle_id=$1 AND cm.user_id=$2 ORDER BY m.created_at ASC LIMIT 200', [request.params.circleId, request.user.id])).rows; return ok(response, { messages }); } catch (error) { next(error); } });
app.post('/api/circles/:circleId/calls', async (request, response, next) => { try { const roomCode = crypto.randomBytes(8).toString('hex'); const call = (await pool.query("INSERT INTO group_calls(circle_id,started_by,room_code) SELECT $1,$2,$3 WHERE EXISTS (SELECT 1 FROM circle_members WHERE circle_id=$1 AND user_id=$2) RETURNING *", [request.params.circleId, request.user.id, roomCode])).rows[0]; if (!call) return fail(response, 403, 'You are not a member of this circle.'); return ok(response, { call }, 201); } catch (error) { next(error); } });
app.get('/api/state', async (request, response, next) => { try { const row = (await pool.query('SELECT dark_mode AS "darkMode",live_location AS "liveLocation",friend_activity AS "friendActivity",digest,discoverable,saved_places AS "savedPlaces",saved_events AS "savedEvents" FROM user_settings WHERE user_id=$1', [request.user.id])).rows[0]; return ok(response, row ? { found: true, ...row, settings: { liveLocation: row.liveLocation, friendActivity: row.friendActivity, digest: row.digest, discoverable: row.discoverable } } : { found: false }); } catch (error) { next(error); } });
app.post('/api/state', async (request, response, next) => { try { const d = request.body; await pool.query(`INSERT INTO user_settings(user_id,dark_mode,live_location,friend_activity,digest,discoverable,saved_places,saved_events) VALUES($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT(user_id) DO UPDATE SET dark_mode=EXCLUDED.dark_mode,live_location=EXCLUDED.live_location,friend_activity=EXCLUDED.friend_activity,digest=EXCLUDED.digest,discoverable=EXCLUDED.discoverable,saved_places=EXCLUDED.saved_places,saved_events=EXCLUDED.saved_events,updated_at=NOW()`, [request.user.id, !!d.darkMode, !!d.settings?.liveLocation, d.settings?.friendActivity !== false, !!d.settings?.digest, d.settings?.discoverable !== false, JSON.stringify(d.savedPlaces || []), JSON.stringify(d.savedEvents || [])]); return ok(response); } catch (error) { next(error); } });

app.use((error, _request, response, _next) => { console.error(error); return fail(response, error.code === '23505' ? 409 : 500, error.code === '23505' ? 'Username, email, or request already exists.' : 'Server error.'); });
app.get('/react', (_request, response) => response.sendFile(path.join(clientDist, 'index.html')));
app.get('*', (_request, response) => response.sendFile(path.join(root, 'socialcircle.html')));

async function initialize() { await pool.query(fs.readFileSync(path.join(root, 'schema.sql'), 'utf8')); const password = process.env.ADMIN_PASSWORD || 'admin@123'; await pool.query(`INSERT INTO users(username,email,password_hash,display_name,is_admin) VALUES('admin','admin@socialcircle.local',$1,'Administrator',TRUE) ON CONFLICT(username) DO UPDATE SET password_hash=EXCLUDED.password_hash,is_admin=TRUE`, [await hashPassword(password)]); }
initialize().catch(error => { console.error('Database startup failed:', error.message); process.exit(1); });
module.exports = { createApp: () => app };
